import { useState } from "react";
import { useMutation, useQueryClient } from "@tanstack/react-query";
import { Activity, ArrowRight, Building2, CheckCircle2, ClipboardCheck, LockKeyhole, Search } from "lucide-react";
import { toast } from "sonner";

import { FacilityCard, SectionHeading } from "@/components/CareComponents";
import { Badge } from "@/components/ui/badge";
import { Button } from "@/components/ui/button";
import { Card, CardContent, CardHeader, CardTitle } from "@/components/ui/card";
import { Input } from "@/components/ui/input";
import { Textarea } from "@/components/ui/textarea";
import { apiPost } from "@/lib/api";
import type { DemoState, DoctorAssessment, Profile, Referral } from "@/types/domain";

function DoctorLookup({ identifier, authorized, pending, onIdentifier, onAuthorized, onLookup }: { identifier: string; authorized: boolean; pending: boolean; onIdentifier: (value: string) => void; onAuthorized: (value: boolean) => void; onLookup: () => void }) {
  return <section className="rounded-[24px] border border-slate-200 bg-white p-6 shadow-sm" data-testid="doctor-lookup-section"><div className="flex flex-col justify-between gap-5 md:flex-row md:items-end"><div><p className="font-mono text-[10px] font-semibold uppercase tracking-[0.2em] text-teal-700">CLINICAL WORKSPACE · DEMO</p><h1 className="mt-2 font-heading text-3xl font-bold tracking-tight text-slate-950">Find the right context, then decide.</h1><p className="mt-2 max-w-2xl text-sm leading-relaxed text-slate-500">Patient access is authorization-led. AI assistance is clearly separate from your confirmed clinical decision.</p></div><div className="flex items-center gap-2 rounded-xl bg-amber-50 px-3 py-2 text-xs text-amber-800"><LockKeyhole size={15} /> Normal access requires authorization</div></div><div className="mt-6 flex flex-col gap-3 sm:flex-row"><div className="relative flex-1"><Search className="absolute left-3 top-1/2 -translate-y-1/2 text-slate-400" size={17} /><Input value={identifier} onChange={(event) => onIdentifier(event.target.value)} className="pl-9" placeholder="Secure patient ID or phone" data-testid="doctor-patient-lookup-input" /></div><label className="flex min-h-10 items-center gap-2 rounded-xl border border-slate-200 px-3 text-sm text-slate-600"><input type="checkbox" checked={authorized} onChange={(event) => onAuthorized(event.target.checked)} className="size-4 accent-teal-600" data-testid="doctor-authorization-checkbox" /> Patient authorization confirmed</label><Button onClick={onLookup} disabled={!authorized || pending} className="bg-teal-700 hover:bg-teal-800" data-testid="doctor-lookup-button">{pending ? "Opening…" : "Find patient"}<ArrowRight size={16} /></Button></div></section>;
}

function PatientSummary({ patient }: { patient: Profile }) {
  return <Card className="border-red-100 bg-white shadow-none"><CardHeader><p className="font-mono text-[10px] uppercase tracking-[0.18em] text-red-700">AUTHORIZED PATIENT</p><CardTitle className="mt-1 font-heading text-xl">{patient.name}, {patient.age}</CardTitle><p className="text-sm text-slate-500">{patient.secure_id} · {patient.location}</p></CardHeader><CardContent className="space-y-3"><div className="rounded-xl bg-red-50 p-3"><p className="text-[11px] font-semibold uppercase tracking-wider text-red-700">Allergies</p><p className="mt-1 font-medium text-slate-800">{patient.allergies.join(", ")}</p></div><div className="rounded-xl bg-slate-50 p-3"><p className="text-[11px] font-semibold uppercase tracking-wider text-slate-500">Current medicines</p><p className="mt-1 text-sm text-slate-800">{patient.medicines.join(", ")}</p></div><div className="rounded-xl bg-slate-50 p-3"><p className="text-[11px] font-semibold uppercase tracking-wider text-slate-500">History</p><p className="mt-1 text-sm text-slate-800">{patient.previous_history.join(", ")}</p></div></CardContent></Card>;
}

function CurrentAssessment({ symptoms, findings, pending, onSymptoms, onFindings, onReview }: { symptoms: string; findings: string; pending: boolean; onSymptoms: (value: string) => void; onFindings: (value: string) => void; onReview: () => void }) {
  return <Card className="border-slate-200 shadow-none"><CardHeader><p className="font-mono text-[10px] uppercase tracking-[0.18em] text-teal-700">CURRENT ASSESSMENT</p><CardTitle className="mt-1 font-heading text-xl">What needs attention today?</CardTitle></CardHeader><CardContent className="space-y-3"><Textarea value={symptoms} onChange={(event) => onSymptoms(event.target.value)} placeholder="Current symptoms" className="min-h-24" data-testid="doctor-symptoms-input" /><Textarea value={findings} onChange={(event) => onFindings(event.target.value)} placeholder="Clinical findings / vitals (optional)" className="min-h-20" data-testid="doctor-findings-input" /><Button onClick={onReview} disabled={!symptoms || pending} className="bg-teal-700 hover:bg-teal-800" data-testid="doctor-ai-review-button">{pending ? "Preparing assistance…" : "Review AI-assisted assessment"}<ClipboardCheck size={16} /></Button></CardContent></Card>;
}

function AssistanceCard({ assistance, onOverride }: { assistance: DoctorAssessment | null; onOverride: () => void }) {
  return <section className="rounded-[24px] border border-amber-200 bg-[#fffbeb] p-5" data-testid="ai-assessment-card"><div className="flex flex-col justify-between gap-3 sm:flex-row sm:items-start"><div><div className="flex items-center gap-2"><div className="grid size-8 place-items-center rounded-xl bg-amber-100 text-amber-700"><Activity size={17} /></div><p className="font-mono text-[10px] font-bold uppercase tracking-[0.18em] text-amber-800">AI-assisted assessment</p></div><h2 className="mt-2 font-heading text-xl font-semibold text-slate-900">Supportive, bounded, editable</h2></div><Badge className="w-fit border-amber-200 bg-amber-100 text-amber-800">DETERMINISTIC DEMO ADAPTER</Badge></div>{assistance ? <AssistanceDetails assistance={assistance} /> : <p className="mt-3 text-sm text-slate-600">Review current symptoms to see a bounded assistance summary. Your decision remains authoritative.</p>}<div className="mt-4 flex flex-wrap gap-2"><Button variant="outline" onClick={onOverride} disabled={!assistance} data-testid="doctor-override-button">Override assistance</Button>{assistance && <Badge className="border-teal-200 bg-teal-50 text-teal-700" data-testid="doctor-decision-authoritative">Doctor decision authoritative</Badge>}</div></section>;
}

function AssistanceDetails({ assistance }: { assistance: DoctorAssessment }) {
  return <div className="mt-4 grid gap-3 md:grid-cols-3"><div className="rounded-xl bg-white p-3"><p className="text-[11px] uppercase tracking-wider text-slate-400">Urgency</p><p className="mt-1 font-semibold text-slate-800">{assistance.urgency}</p></div><div className="rounded-xl bg-white p-3"><p className="text-[11px] uppercase tracking-wider text-slate-400">Care requirement</p><p className="mt-1 font-semibold text-slate-800">{assistance.care_requirement}</p></div><div className="rounded-xl bg-white p-3"><p className="text-[11px] uppercase tracking-wider text-slate-400">Suggested capabilities</p><p className="mt-1 text-sm font-semibold text-slate-800">{assistance.suggested_capabilities.join(" · ")}</p></div><div className="rounded-xl border border-amber-100 bg-amber-50/60 p-3 text-sm leading-relaxed text-slate-700 md:col-span-3">{assistance.summary}</div></div>;
}

function FacilityMatching({ state, selected, assistance, sent, pending, onSelect, onSend }: { state: DemoState; selected: string; assistance: DoctorAssessment | null; sent: Referral | null; pending: boolean; onSelect: (id: string) => void; onSend: () => void }) {
  return <section data-testid="facility-matching-section"><SectionHeading eyebrow="CAPABILITY MATCHING" title="Suitable Facilities for This Care Requirement" description="Capabilities are matched first. The fixed demo order is only a tie-breaker — there is no unexplained best-hospital score." icon={Building2} /><div className="grid gap-3 lg:grid-cols-3">{state.facilities.map((facility) => <FacilityCard key={facility.id} facility={facility} selected={selected === facility.id} onSelect={() => onSelect(facility.id)} />)}</div><div className="mt-5 rounded-2xl border border-slate-200 bg-white p-4"><div className="flex flex-col justify-between gap-3 sm:flex-row sm:items-center"><div><p className="text-sm font-semibold text-slate-800">Ready to create a referral?</p><p className="text-xs text-slate-500">Review the selected facility, then confirm/send. The hospital queue will update from stored data.</p></div><Button onClick={onSend} disabled={!assistance || !selected || pending} className="bg-teal-700 hover:bg-teal-800" data-testid="doctor-confirm-referral-button">{pending ? "Sending…" : "Confirm & send referral"}<ArrowRight size={16} /></Button></div>{sent && <div className="mt-4 flex items-start gap-3 rounded-xl bg-emerald-50 p-3 text-sm text-emerald-800" data-testid="doctor-referral-success"><CheckCircle2 size={18} /><div><p className="font-semibold">Referral Created. Hospital notified.</p><p className="mt-1 text-xs">{sent.id} · {sent.facility_name}</p></div></div>}</div></section>;
}

export default function DoctorWorkspace({ state }: { state: DemoState }) {
  const queryClient = useQueryClient();
  const [identifier, setIdentifier] = useState("CARE-PT-001");
  const [authorized, setAuthorized] = useState(false);
  const [patient, setPatient] = useState<Profile | null>(null);
  const [symptoms, setSymptoms] = useState("Persistent tiredness and mild chest discomfort after exertion.");
  const [findings, setFindings] = useState("");
  const [assistance, setAssistance] = useState<DoctorAssessment | null>(null);
  const [selectedFacility, setSelectedFacility] = useState("");
  const [sentReferral, setSentReferral] = useState<Referral | null>(null);
  const lookup = useMutation({ mutationFn: () => apiPost<{ patient: Profile }>("/doctor/patients/lookup", { identifier, authorization_granted: authorized }), onSuccess: (result) => { setPatient(result.patient); toast.success("Authorized patient workspace opened"); }, onError: () => toast.error("Confirm patient authorization before lookup") });
  const review = useMutation({ mutationFn: () => apiPost<DoctorAssessment>("/doctor/assessment-assistance", { symptoms, findings }), onSuccess: setAssistance });
  const referral = useMutation({ mutationFn: () => apiPost<Referral>("/referrals", { patient_id: patient?.id, facility_id: selectedFacility, reason: "Routine clinical review after current assessment", care_requirement: assistance?.care_requirement || "Primary care review", urgency: assistance?.urgency || "Routine", symptoms, findings, ai_assessment: assistance?.summary || "", doctor_decision: "Confirmed by doctor after review and override controls." }), onSuccess: (result) => { setSentReferral(result); queryClient.invalidateQueries({ queryKey: ["demo-state"] }); toast.success("Referral sent to hospital queue"); } });
  const override = () => { if (assistance) setAssistance({ ...assistance, summary: "Doctor override: routine specialist review recommended based on the current findings." }); };

  return <div className="space-y-6" data-testid="doctor-workspace"><DoctorLookup identifier={identifier} authorized={authorized} pending={lookup.isPending} onIdentifier={setIdentifier} onAuthorized={setAuthorized} onLookup={() => lookup.mutate()} />{patient && <><section className="grid gap-4 lg:grid-cols-[.8fr_1.2fr]" data-testid="doctor-patient-summary"><PatientSummary patient={patient} /><CurrentAssessment symptoms={symptoms} findings={findings} pending={review.isPending} onSymptoms={setSymptoms} onFindings={setFindings} onReview={() => review.mutate()} /></section><AssistanceCard assistance={assistance} onOverride={override} /><FacilityMatching state={state} selected={selectedFacility} assistance={assistance} sent={sentReferral} pending={referral.isPending} onSelect={setSelectedFacility} onSend={() => referral.mutate()} /></>}</div>;
}